baseURL = "http://example.com/"
languageCode = "en-us"
title = "TestMyRobot"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "AWS"
    description = "A repository of robot test scenarios."
    githubUsername = "jerwallace"
    accent = "#ff9400"
    showBorder = true
    copyright = "© 2020 AWS RoboMaker"
    backgroundColor = "white"
    font = "Amazon Ember" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/tests/"
    name = "Robot Tests"
    weight = 3

